//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace diplom2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Komp
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Komp()
        {
            this.Status2 = new HashSet<Status2>();
        }
    
        public int ID_Komplect { get; set; }
        public int Art { get; set; }
        public string Name { get; set; }
        public Nullable<short> Kategoria { get; set; }
        public Nullable<int> Price { get; set; }
        public Nullable<int> Cost { get; set; }
        public Nullable<int> Quantity { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
    
        public virtual Kategoria Kategoria1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Status2> Status2 { get; set; }
    }
}
