//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace diplom2
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DP2Entities : DbContext
    {
        private static DP2Entities _context;
        public DP2Entities()
            : base("name=DP2Entities")
        {
        }

        public static DP2Entities GetContext()
        {
            if (_context == null)
                _context = new DP2Entities();
            return _context;
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Kategoria> Kategoria { get; set; }
        public virtual DbSet<Komp> Komp { get; set; }
        public virtual DbSet<Status> Status { get; set; }
        public virtual DbSet<Status2> Status2 { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Tex> Tex { get; set; }
        public virtual DbSet<Type> Type { get; set; }
    }
}
