//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace diplom2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Status2
    {
        public short ID_Sklad { get; set; }
        public Nullable<short> ID_Tex { get; set; }
        public Nullable<int> ID_Komplect { get; set; }
    
        public virtual Komp Komp { get; set; }
        public virtual Tex Tex { get; set; }
    }
}
